// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/budget.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BudgetService_GetBudget_FullMethodName        = "/wealthjourney.budget.v1.BudgetService/GetBudget"
	BudgetService_ListBudgets_FullMethodName      = "/wealthjourney.budget.v1.BudgetService/ListBudgets"
	BudgetService_CreateBudget_FullMethodName     = "/wealthjourney.budget.v1.BudgetService/CreateBudget"
	BudgetService_UpdateBudget_FullMethodName     = "/wealthjourney.budget.v1.BudgetService/UpdateBudget"
	BudgetService_DeleteBudget_FullMethodName     = "/wealthjourney.budget.v1.BudgetService/DeleteBudget"
	BudgetService_GetBudgetItems_FullMethodName   = "/wealthjourney.budget.v1.BudgetService/GetBudgetItems"
	BudgetService_CreateBudgetItem_FullMethodName = "/wealthjourney.budget.v1.BudgetService/CreateBudgetItem"
	BudgetService_UpdateBudgetItem_FullMethodName = "/wealthjourney.budget.v1.BudgetService/UpdateBudgetItem"
	BudgetService_DeleteBudgetItem_FullMethodName = "/wealthjourney.budget.v1.BudgetService/DeleteBudgetItem"
)

// BudgetServiceClient is the client API for BudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BudgetServiceClient interface {
	// Get a budget by ID
	GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error)
	// List all budgets for authenticated user with pagination
	ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error)
	// Create a new budget
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error)
	// Update budget information
	UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*UpdateBudgetResponse, error)
	// Delete a budget
	DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*DeleteBudgetResponse, error)
	// Get budget items for a budget
	GetBudgetItems(ctx context.Context, in *GetBudgetItemsRequest, opts ...grpc.CallOption) (*GetBudgetItemsResponse, error)
	// Create a budget item
	CreateBudgetItem(ctx context.Context, in *CreateBudgetItemRequest, opts ...grpc.CallOption) (*CreateBudgetItemResponse, error)
	// Update a budget item
	UpdateBudgetItem(ctx context.Context, in *UpdateBudgetItemRequest, opts ...grpc.CallOption) (*UpdateBudgetItemResponse, error)
	// Delete a budget item
	DeleteBudgetItem(ctx context.Context, in *DeleteBudgetItemRequest, opts ...grpc.CallOption) (*DeleteBudgetItemResponse, error)
}

type budgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetServiceClient(cc grpc.ClientConnInterface) BudgetServiceClient {
	return &budgetServiceClient{cc}
}

func (c *budgetServiceClient) GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error) {
	out := new(GetBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_GetBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error) {
	out := new(ListBudgetsResponse)
	err := c.cc.Invoke(ctx, BudgetService_ListBudgets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*CreateBudgetResponse, error) {
	out := new(CreateBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_CreateBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*UpdateBudgetResponse, error) {
	out := new(UpdateBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_UpdateBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) DeleteBudget(ctx context.Context, in *DeleteBudgetRequest, opts ...grpc.CallOption) (*DeleteBudgetResponse, error) {
	out := new(DeleteBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_DeleteBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) GetBudgetItems(ctx context.Context, in *GetBudgetItemsRequest, opts ...grpc.CallOption) (*GetBudgetItemsResponse, error) {
	out := new(GetBudgetItemsResponse)
	err := c.cc.Invoke(ctx, BudgetService_GetBudgetItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) CreateBudgetItem(ctx context.Context, in *CreateBudgetItemRequest, opts ...grpc.CallOption) (*CreateBudgetItemResponse, error) {
	out := new(CreateBudgetItemResponse)
	err := c.cc.Invoke(ctx, BudgetService_CreateBudgetItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) UpdateBudgetItem(ctx context.Context, in *UpdateBudgetItemRequest, opts ...grpc.CallOption) (*UpdateBudgetItemResponse, error) {
	out := new(UpdateBudgetItemResponse)
	err := c.cc.Invoke(ctx, BudgetService_UpdateBudgetItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) DeleteBudgetItem(ctx context.Context, in *DeleteBudgetItemRequest, opts ...grpc.CallOption) (*DeleteBudgetItemResponse, error) {
	out := new(DeleteBudgetItemResponse)
	err := c.cc.Invoke(ctx, BudgetService_DeleteBudgetItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetServiceServer is the server API for BudgetService service.
// All implementations must embed UnimplementedBudgetServiceServer
// for forward compatibility
type BudgetServiceServer interface {
	// Get a budget by ID
	GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error)
	// List all budgets for authenticated user with pagination
	ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error)
	// Create a new budget
	CreateBudget(context.Context, *CreateBudgetRequest) (*CreateBudgetResponse, error)
	// Update budget information
	UpdateBudget(context.Context, *UpdateBudgetRequest) (*UpdateBudgetResponse, error)
	// Delete a budget
	DeleteBudget(context.Context, *DeleteBudgetRequest) (*DeleteBudgetResponse, error)
	// Get budget items for a budget
	GetBudgetItems(context.Context, *GetBudgetItemsRequest) (*GetBudgetItemsResponse, error)
	// Create a budget item
	CreateBudgetItem(context.Context, *CreateBudgetItemRequest) (*CreateBudgetItemResponse, error)
	// Update a budget item
	UpdateBudgetItem(context.Context, *UpdateBudgetItemRequest) (*UpdateBudgetItemResponse, error)
	// Delete a budget item
	DeleteBudgetItem(context.Context, *DeleteBudgetItemRequest) (*DeleteBudgetItemResponse, error)
	mustEmbedUnimplementedBudgetServiceServer()
}

// UnimplementedBudgetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBudgetServiceServer struct {
}

func (UnimplementedBudgetServiceServer) GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudget not implemented")
}
func (UnimplementedBudgetServiceServer) ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBudgets not implemented")
}
func (UnimplementedBudgetServiceServer) CreateBudget(context.Context, *CreateBudgetRequest) (*CreateBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBudget not implemented")
}
func (UnimplementedBudgetServiceServer) UpdateBudget(context.Context, *UpdateBudgetRequest) (*UpdateBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBudget not implemented")
}
func (UnimplementedBudgetServiceServer) DeleteBudget(context.Context, *DeleteBudgetRequest) (*DeleteBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBudget not implemented")
}
func (UnimplementedBudgetServiceServer) GetBudgetItems(context.Context, *GetBudgetItemsRequest) (*GetBudgetItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetItems not implemented")
}
func (UnimplementedBudgetServiceServer) CreateBudgetItem(context.Context, *CreateBudgetItemRequest) (*CreateBudgetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBudgetItem not implemented")
}
func (UnimplementedBudgetServiceServer) UpdateBudgetItem(context.Context, *UpdateBudgetItemRequest) (*UpdateBudgetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBudgetItem not implemented")
}
func (UnimplementedBudgetServiceServer) DeleteBudgetItem(context.Context, *DeleteBudgetItemRequest) (*DeleteBudgetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBudgetItem not implemented")
}
func (UnimplementedBudgetServiceServer) mustEmbedUnimplementedBudgetServiceServer() {}

// UnsafeBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BudgetServiceServer will
// result in compilation errors.
type UnsafeBudgetServiceServer interface {
	mustEmbedUnimplementedBudgetServiceServer()
}

func RegisterBudgetServiceServer(s grpc.ServiceRegistrar, srv BudgetServiceServer) {
	s.RegisterService(&BudgetService_ServiceDesc, srv)
}

func _BudgetService_GetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).GetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_GetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).GetBudget(ctx, req.(*GetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_ListBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).ListBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_ListBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).ListBudgets(ctx, req.(*ListBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_CreateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_UpdateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).UpdateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_UpdateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).UpdateBudget(ctx, req.(*UpdateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_DeleteBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).DeleteBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_DeleteBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).DeleteBudget(ctx, req.(*DeleteBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_GetBudgetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).GetBudgetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_GetBudgetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).GetBudgetItems(ctx, req.(*GetBudgetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_CreateBudgetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).CreateBudgetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_CreateBudgetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).CreateBudgetItem(ctx, req.(*CreateBudgetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_UpdateBudgetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).UpdateBudgetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_UpdateBudgetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).UpdateBudgetItem(ctx, req.(*UpdateBudgetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_DeleteBudgetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBudgetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).DeleteBudgetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_DeleteBudgetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).DeleteBudgetItem(ctx, req.(*DeleteBudgetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BudgetService_ServiceDesc is the grpc.ServiceDesc for BudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.budget.v1.BudgetService",
	HandlerType: (*BudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBudget",
			Handler:    _BudgetService_GetBudget_Handler,
		},
		{
			MethodName: "ListBudgets",
			Handler:    _BudgetService_ListBudgets_Handler,
		},
		{
			MethodName: "CreateBudget",
			Handler:    _BudgetService_CreateBudget_Handler,
		},
		{
			MethodName: "UpdateBudget",
			Handler:    _BudgetService_UpdateBudget_Handler,
		},
		{
			MethodName: "DeleteBudget",
			Handler:    _BudgetService_DeleteBudget_Handler,
		},
		{
			MethodName: "GetBudgetItems",
			Handler:    _BudgetService_GetBudgetItems_Handler,
		},
		{
			MethodName: "CreateBudgetItem",
			Handler:    _BudgetService_CreateBudgetItem_Handler,
		},
		{
			MethodName: "UpdateBudgetItem",
			Handler:    _BudgetService_UpdateBudgetItem_Handler,
		},
		{
			MethodName: "DeleteBudgetItem",
			Handler:    _BudgetService_DeleteBudgetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/budget.proto",
}
