// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/import.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ImportService_UploadStatementFile_FullMethodName = "/wealthjourney.import.v1.ImportService/UploadStatementFile"
	ImportService_ParseStatement_FullMethodName      = "/wealthjourney.import.v1.ImportService/ParseStatement"
	ImportService_ConvertCurrency_FullMethodName     = "/wealthjourney.import.v1.ImportService/ConvertCurrency"
	ImportService_DetectDuplicates_FullMethodName    = "/wealthjourney.import.v1.ImportService/DetectDuplicates"
	ImportService_ExecuteImport_FullMethodName       = "/wealthjourney.import.v1.ImportService/ExecuteImport"
	ImportService_ListBankTemplates_FullMethodName   = "/wealthjourney.import.v1.ImportService/ListBankTemplates"
	ImportService_GetImportHistory_FullMethodName    = "/wealthjourney.import.v1.ImportService/GetImportHistory"
	ImportService_UndoImport_FullMethodName          = "/wealthjourney.import.v1.ImportService/UndoImport"
	ImportService_ListExcelSheets_FullMethodName     = "/wealthjourney.import.v1.ImportService/ListExcelSheets"
	ImportService_CreateUserTemplate_FullMethodName  = "/wealthjourney.import.v1.ImportService/CreateUserTemplate"
	ImportService_ListUserTemplates_FullMethodName   = "/wealthjourney.import.v1.ImportService/ListUserTemplates"
	ImportService_GetUserTemplate_FullMethodName     = "/wealthjourney.import.v1.ImportService/GetUserTemplate"
	ImportService_UpdateUserTemplate_FullMethodName  = "/wealthjourney.import.v1.ImportService/UpdateUserTemplate"
	ImportService_DeleteUserTemplate_FullMethodName  = "/wealthjourney.import.v1.ImportService/DeleteUserTemplate"
	ImportService_GetJobStatus_FullMethodName        = "/wealthjourney.import.v1.ImportService/GetJobStatus"
	ImportService_CancelJob_FullMethodName           = "/wealthjourney.import.v1.ImportService/CancelJob"
	ImportService_ListUserJobs_FullMethodName        = "/wealthjourney.import.v1.ImportService/ListUserJobs"
)

// ImportServiceClient is the client API for ImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportServiceClient interface {
	// Upload file and initiate parsing
	UploadStatementFile(ctx context.Context, in *UploadStatementFileRequest, opts ...grpc.CallOption) (*UploadStatementFileResponse, error)
	// Parse uploaded file with bank template
	ParseStatement(ctx context.Context, in *ParseStatementRequest, opts ...grpc.CallOption) (*ParseStatementResponse, error)
	// Convert currencies for imported transactions
	ConvertCurrency(ctx context.Context, in *ConvertCurrencyRequest, opts ...grpc.CallOption) (*ConvertCurrencyResponse, error)
	// Detect duplicates for imported transactions
	DetectDuplicates(ctx context.Context, in *DetectDuplicatesRequest, opts ...grpc.CallOption) (*DetectDuplicatesResponse, error)
	// Execute import of reviewed transactions
	ExecuteImport(ctx context.Context, in *ExecuteImportRequest, opts ...grpc.CallOption) (*ExecuteImportResponse, error)
	// List available bank templates
	ListBankTemplates(ctx context.Context, in *ListBankTemplatesRequest, opts ...grpc.CallOption) (*ListBankTemplatesResponse, error)
	// Get import history
	GetImportHistory(ctx context.Context, in *GetImportHistoryRequest, opts ...grpc.CallOption) (*GetImportHistoryResponse, error)
	// Undo import (within 24 hours)
	UndoImport(ctx context.Context, in *UndoImportRequest, opts ...grpc.CallOption) (*UndoImportResponse, error)
	// List Excel sheets for multi-sheet files
	ListExcelSheets(ctx context.Context, in *ListExcelSheetsRequest, opts ...grpc.CallOption) (*ListExcelSheetsResponse, error)
	// User Template Management
	CreateUserTemplate(ctx context.Context, in *CreateUserTemplateRequest, opts ...grpc.CallOption) (*CreateUserTemplateResponse, error)
	ListUserTemplates(ctx context.Context, in *ListUserTemplatesRequest, opts ...grpc.CallOption) (*ListUserTemplatesResponse, error)
	GetUserTemplate(ctx context.Context, in *GetUserTemplateRequest, opts ...grpc.CallOption) (*GetUserTemplateResponse, error)
	UpdateUserTemplate(ctx context.Context, in *UpdateUserTemplateRequest, opts ...grpc.CallOption) (*UpdateUserTemplateResponse, error)
	DeleteUserTemplate(ctx context.Context, in *DeleteUserTemplateRequest, opts ...grpc.CallOption) (*DeleteUserTemplateResponse, error)
	// Background Job Management
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	ListUserJobs(ctx context.Context, in *ListUserJobsRequest, opts ...grpc.CallOption) (*ListUserJobsResponse, error)
}

type importServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportServiceClient(cc grpc.ClientConnInterface) ImportServiceClient {
	return &importServiceClient{cc}
}

func (c *importServiceClient) UploadStatementFile(ctx context.Context, in *UploadStatementFileRequest, opts ...grpc.CallOption) (*UploadStatementFileResponse, error) {
	out := new(UploadStatementFileResponse)
	err := c.cc.Invoke(ctx, ImportService_UploadStatementFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ParseStatement(ctx context.Context, in *ParseStatementRequest, opts ...grpc.CallOption) (*ParseStatementResponse, error) {
	out := new(ParseStatementResponse)
	err := c.cc.Invoke(ctx, ImportService_ParseStatement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ConvertCurrency(ctx context.Context, in *ConvertCurrencyRequest, opts ...grpc.CallOption) (*ConvertCurrencyResponse, error) {
	out := new(ConvertCurrencyResponse)
	err := c.cc.Invoke(ctx, ImportService_ConvertCurrency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) DetectDuplicates(ctx context.Context, in *DetectDuplicatesRequest, opts ...grpc.CallOption) (*DetectDuplicatesResponse, error) {
	out := new(DetectDuplicatesResponse)
	err := c.cc.Invoke(ctx, ImportService_DetectDuplicates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ExecuteImport(ctx context.Context, in *ExecuteImportRequest, opts ...grpc.CallOption) (*ExecuteImportResponse, error) {
	out := new(ExecuteImportResponse)
	err := c.cc.Invoke(ctx, ImportService_ExecuteImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ListBankTemplates(ctx context.Context, in *ListBankTemplatesRequest, opts ...grpc.CallOption) (*ListBankTemplatesResponse, error) {
	out := new(ListBankTemplatesResponse)
	err := c.cc.Invoke(ctx, ImportService_ListBankTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) GetImportHistory(ctx context.Context, in *GetImportHistoryRequest, opts ...grpc.CallOption) (*GetImportHistoryResponse, error) {
	out := new(GetImportHistoryResponse)
	err := c.cc.Invoke(ctx, ImportService_GetImportHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) UndoImport(ctx context.Context, in *UndoImportRequest, opts ...grpc.CallOption) (*UndoImportResponse, error) {
	out := new(UndoImportResponse)
	err := c.cc.Invoke(ctx, ImportService_UndoImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ListExcelSheets(ctx context.Context, in *ListExcelSheetsRequest, opts ...grpc.CallOption) (*ListExcelSheetsResponse, error) {
	out := new(ListExcelSheetsResponse)
	err := c.cc.Invoke(ctx, ImportService_ListExcelSheets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) CreateUserTemplate(ctx context.Context, in *CreateUserTemplateRequest, opts ...grpc.CallOption) (*CreateUserTemplateResponse, error) {
	out := new(CreateUserTemplateResponse)
	err := c.cc.Invoke(ctx, ImportService_CreateUserTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ListUserTemplates(ctx context.Context, in *ListUserTemplatesRequest, opts ...grpc.CallOption) (*ListUserTemplatesResponse, error) {
	out := new(ListUserTemplatesResponse)
	err := c.cc.Invoke(ctx, ImportService_ListUserTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) GetUserTemplate(ctx context.Context, in *GetUserTemplateRequest, opts ...grpc.CallOption) (*GetUserTemplateResponse, error) {
	out := new(GetUserTemplateResponse)
	err := c.cc.Invoke(ctx, ImportService_GetUserTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) UpdateUserTemplate(ctx context.Context, in *UpdateUserTemplateRequest, opts ...grpc.CallOption) (*UpdateUserTemplateResponse, error) {
	out := new(UpdateUserTemplateResponse)
	err := c.cc.Invoke(ctx, ImportService_UpdateUserTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) DeleteUserTemplate(ctx context.Context, in *DeleteUserTemplateRequest, opts ...grpc.CallOption) (*DeleteUserTemplateResponse, error) {
	out := new(DeleteUserTemplateResponse)
	err := c.cc.Invoke(ctx, ImportService_DeleteUserTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, ImportService_GetJobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, ImportService_CancelJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ListUserJobs(ctx context.Context, in *ListUserJobsRequest, opts ...grpc.CallOption) (*ListUserJobsResponse, error) {
	out := new(ListUserJobsResponse)
	err := c.cc.Invoke(ctx, ImportService_ListUserJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportServiceServer is the server API for ImportService service.
// All implementations must embed UnimplementedImportServiceServer
// for forward compatibility
type ImportServiceServer interface {
	// Upload file and initiate parsing
	UploadStatementFile(context.Context, *UploadStatementFileRequest) (*UploadStatementFileResponse, error)
	// Parse uploaded file with bank template
	ParseStatement(context.Context, *ParseStatementRequest) (*ParseStatementResponse, error)
	// Convert currencies for imported transactions
	ConvertCurrency(context.Context, *ConvertCurrencyRequest) (*ConvertCurrencyResponse, error)
	// Detect duplicates for imported transactions
	DetectDuplicates(context.Context, *DetectDuplicatesRequest) (*DetectDuplicatesResponse, error)
	// Execute import of reviewed transactions
	ExecuteImport(context.Context, *ExecuteImportRequest) (*ExecuteImportResponse, error)
	// List available bank templates
	ListBankTemplates(context.Context, *ListBankTemplatesRequest) (*ListBankTemplatesResponse, error)
	// Get import history
	GetImportHistory(context.Context, *GetImportHistoryRequest) (*GetImportHistoryResponse, error)
	// Undo import (within 24 hours)
	UndoImport(context.Context, *UndoImportRequest) (*UndoImportResponse, error)
	// List Excel sheets for multi-sheet files
	ListExcelSheets(context.Context, *ListExcelSheetsRequest) (*ListExcelSheetsResponse, error)
	// User Template Management
	CreateUserTemplate(context.Context, *CreateUserTemplateRequest) (*CreateUserTemplateResponse, error)
	ListUserTemplates(context.Context, *ListUserTemplatesRequest) (*ListUserTemplatesResponse, error)
	GetUserTemplate(context.Context, *GetUserTemplateRequest) (*GetUserTemplateResponse, error)
	UpdateUserTemplate(context.Context, *UpdateUserTemplateRequest) (*UpdateUserTemplateResponse, error)
	DeleteUserTemplate(context.Context, *DeleteUserTemplateRequest) (*DeleteUserTemplateResponse, error)
	// Background Job Management
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	ListUserJobs(context.Context, *ListUserJobsRequest) (*ListUserJobsResponse, error)
	mustEmbedUnimplementedImportServiceServer()
}

// UnimplementedImportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImportServiceServer struct {
}

func (UnimplementedImportServiceServer) UploadStatementFile(context.Context, *UploadStatementFileRequest) (*UploadStatementFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStatementFile not implemented")
}
func (UnimplementedImportServiceServer) ParseStatement(context.Context, *ParseStatementRequest) (*ParseStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseStatement not implemented")
}
func (UnimplementedImportServiceServer) ConvertCurrency(context.Context, *ConvertCurrencyRequest) (*ConvertCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertCurrency not implemented")
}
func (UnimplementedImportServiceServer) DetectDuplicates(context.Context, *DetectDuplicatesRequest) (*DetectDuplicatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectDuplicates not implemented")
}
func (UnimplementedImportServiceServer) ExecuteImport(context.Context, *ExecuteImportRequest) (*ExecuteImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteImport not implemented")
}
func (UnimplementedImportServiceServer) ListBankTemplates(context.Context, *ListBankTemplatesRequest) (*ListBankTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBankTemplates not implemented")
}
func (UnimplementedImportServiceServer) GetImportHistory(context.Context, *GetImportHistoryRequest) (*GetImportHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImportHistory not implemented")
}
func (UnimplementedImportServiceServer) UndoImport(context.Context, *UndoImportRequest) (*UndoImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoImport not implemented")
}
func (UnimplementedImportServiceServer) ListExcelSheets(context.Context, *ListExcelSheetsRequest) (*ListExcelSheetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExcelSheets not implemented")
}
func (UnimplementedImportServiceServer) CreateUserTemplate(context.Context, *CreateUserTemplateRequest) (*CreateUserTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserTemplate not implemented")
}
func (UnimplementedImportServiceServer) ListUserTemplates(context.Context, *ListUserTemplatesRequest) (*ListUserTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserTemplates not implemented")
}
func (UnimplementedImportServiceServer) GetUserTemplate(context.Context, *GetUserTemplateRequest) (*GetUserTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTemplate not implemented")
}
func (UnimplementedImportServiceServer) UpdateUserTemplate(context.Context, *UpdateUserTemplateRequest) (*UpdateUserTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserTemplate not implemented")
}
func (UnimplementedImportServiceServer) DeleteUserTemplate(context.Context, *DeleteUserTemplateRequest) (*DeleteUserTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserTemplate not implemented")
}
func (UnimplementedImportServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedImportServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedImportServiceServer) ListUserJobs(context.Context, *ListUserJobsRequest) (*ListUserJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserJobs not implemented")
}
func (UnimplementedImportServiceServer) mustEmbedUnimplementedImportServiceServer() {}

// UnsafeImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportServiceServer will
// result in compilation errors.
type UnsafeImportServiceServer interface {
	mustEmbedUnimplementedImportServiceServer()
}

func RegisterImportServiceServer(s grpc.ServiceRegistrar, srv ImportServiceServer) {
	s.RegisterService(&ImportService_ServiceDesc, srv)
}

func _ImportService_UploadStatementFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStatementFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).UploadStatementFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_UploadStatementFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).UploadStatementFile(ctx, req.(*UploadStatementFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ParseStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ParseStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ParseStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ParseStatement(ctx, req.(*ParseStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ConvertCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ConvertCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ConvertCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ConvertCurrency(ctx, req.(*ConvertCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_DetectDuplicates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectDuplicatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).DetectDuplicates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_DetectDuplicates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).DetectDuplicates(ctx, req.(*DetectDuplicatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ExecuteImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ExecuteImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ExecuteImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ExecuteImport(ctx, req.(*ExecuteImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ListBankTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBankTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ListBankTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ListBankTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ListBankTemplates(ctx, req.(*ListBankTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_GetImportHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).GetImportHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_GetImportHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).GetImportHistory(ctx, req.(*GetImportHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_UndoImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).UndoImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_UndoImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).UndoImport(ctx, req.(*UndoImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ListExcelSheets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExcelSheetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ListExcelSheets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ListExcelSheets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ListExcelSheets(ctx, req.(*ListExcelSheetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_CreateUserTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).CreateUserTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_CreateUserTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).CreateUserTemplate(ctx, req.(*CreateUserTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ListUserTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ListUserTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ListUserTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ListUserTemplates(ctx, req.(*ListUserTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_GetUserTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).GetUserTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_GetUserTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).GetUserTemplate(ctx, req.(*GetUserTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_UpdateUserTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).UpdateUserTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_UpdateUserTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).UpdateUserTemplate(ctx, req.(*UpdateUserTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_DeleteUserTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).DeleteUserTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_DeleteUserTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).DeleteUserTemplate(ctx, req.(*DeleteUserTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ListUserJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ListUserJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ListUserJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ListUserJobs(ctx, req.(*ListUserJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportService_ServiceDesc is the grpc.ServiceDesc for ImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.import.v1.ImportService",
	HandlerType: (*ImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadStatementFile",
			Handler:    _ImportService_UploadStatementFile_Handler,
		},
		{
			MethodName: "ParseStatement",
			Handler:    _ImportService_ParseStatement_Handler,
		},
		{
			MethodName: "ConvertCurrency",
			Handler:    _ImportService_ConvertCurrency_Handler,
		},
		{
			MethodName: "DetectDuplicates",
			Handler:    _ImportService_DetectDuplicates_Handler,
		},
		{
			MethodName: "ExecuteImport",
			Handler:    _ImportService_ExecuteImport_Handler,
		},
		{
			MethodName: "ListBankTemplates",
			Handler:    _ImportService_ListBankTemplates_Handler,
		},
		{
			MethodName: "GetImportHistory",
			Handler:    _ImportService_GetImportHistory_Handler,
		},
		{
			MethodName: "UndoImport",
			Handler:    _ImportService_UndoImport_Handler,
		},
		{
			MethodName: "ListExcelSheets",
			Handler:    _ImportService_ListExcelSheets_Handler,
		},
		{
			MethodName: "CreateUserTemplate",
			Handler:    _ImportService_CreateUserTemplate_Handler,
		},
		{
			MethodName: "ListUserTemplates",
			Handler:    _ImportService_ListUserTemplates_Handler,
		},
		{
			MethodName: "GetUserTemplate",
			Handler:    _ImportService_GetUserTemplate_Handler,
		},
		{
			MethodName: "UpdateUserTemplate",
			Handler:    _ImportService_UpdateUserTemplate_Handler,
		},
		{
			MethodName: "DeleteUserTemplate",
			Handler:    _ImportService_DeleteUserTemplate_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _ImportService_GetJobStatus_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _ImportService_CancelJob_Handler,
		},
		{
			MethodName: "ListUserJobs",
			Handler:    _ImportService_ListUserJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/import.proto",
}
