// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/import.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ImportService_UploadStatementFile_FullMethodName = "/wealthjourney.import.v1.ImportService/UploadStatementFile"
	ImportService_ParseStatement_FullMethodName      = "/wealthjourney.import.v1.ImportService/ParseStatement"
	ImportService_DetectDuplicates_FullMethodName    = "/wealthjourney.import.v1.ImportService/DetectDuplicates"
	ImportService_ExecuteImport_FullMethodName       = "/wealthjourney.import.v1.ImportService/ExecuteImport"
	ImportService_ListBankTemplates_FullMethodName   = "/wealthjourney.import.v1.ImportService/ListBankTemplates"
	ImportService_GetImportHistory_FullMethodName    = "/wealthjourney.import.v1.ImportService/GetImportHistory"
	ImportService_UndoImport_FullMethodName          = "/wealthjourney.import.v1.ImportService/UndoImport"
)

// ImportServiceClient is the client API for ImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportServiceClient interface {
	// Upload file and initiate parsing
	UploadStatementFile(ctx context.Context, in *UploadStatementFileRequest, opts ...grpc.CallOption) (*UploadStatementFileResponse, error)
	// Parse uploaded file with bank template
	ParseStatement(ctx context.Context, in *ParseStatementRequest, opts ...grpc.CallOption) (*ParseStatementResponse, error)
	// Detect duplicates for imported transactions
	DetectDuplicates(ctx context.Context, in *DetectDuplicatesRequest, opts ...grpc.CallOption) (*DetectDuplicatesResponse, error)
	// Execute import of reviewed transactions
	ExecuteImport(ctx context.Context, in *ExecuteImportRequest, opts ...grpc.CallOption) (*ExecuteImportResponse, error)
	// List available bank templates
	ListBankTemplates(ctx context.Context, in *ListBankTemplatesRequest, opts ...grpc.CallOption) (*ListBankTemplatesResponse, error)
	// Get import history
	GetImportHistory(ctx context.Context, in *GetImportHistoryRequest, opts ...grpc.CallOption) (*GetImportHistoryResponse, error)
	// Undo import (within 24 hours)
	UndoImport(ctx context.Context, in *UndoImportRequest, opts ...grpc.CallOption) (*UndoImportResponse, error)
}

type importServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportServiceClient(cc grpc.ClientConnInterface) ImportServiceClient {
	return &importServiceClient{cc}
}

func (c *importServiceClient) UploadStatementFile(ctx context.Context, in *UploadStatementFileRequest, opts ...grpc.CallOption) (*UploadStatementFileResponse, error) {
	out := new(UploadStatementFileResponse)
	err := c.cc.Invoke(ctx, ImportService_UploadStatementFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ParseStatement(ctx context.Context, in *ParseStatementRequest, opts ...grpc.CallOption) (*ParseStatementResponse, error) {
	out := new(ParseStatementResponse)
	err := c.cc.Invoke(ctx, ImportService_ParseStatement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) DetectDuplicates(ctx context.Context, in *DetectDuplicatesRequest, opts ...grpc.CallOption) (*DetectDuplicatesResponse, error) {
	out := new(DetectDuplicatesResponse)
	err := c.cc.Invoke(ctx, ImportService_DetectDuplicates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ExecuteImport(ctx context.Context, in *ExecuteImportRequest, opts ...grpc.CallOption) (*ExecuteImportResponse, error) {
	out := new(ExecuteImportResponse)
	err := c.cc.Invoke(ctx, ImportService_ExecuteImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ListBankTemplates(ctx context.Context, in *ListBankTemplatesRequest, opts ...grpc.CallOption) (*ListBankTemplatesResponse, error) {
	out := new(ListBankTemplatesResponse)
	err := c.cc.Invoke(ctx, ImportService_ListBankTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) GetImportHistory(ctx context.Context, in *GetImportHistoryRequest, opts ...grpc.CallOption) (*GetImportHistoryResponse, error) {
	out := new(GetImportHistoryResponse)
	err := c.cc.Invoke(ctx, ImportService_GetImportHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) UndoImport(ctx context.Context, in *UndoImportRequest, opts ...grpc.CallOption) (*UndoImportResponse, error) {
	out := new(UndoImportResponse)
	err := c.cc.Invoke(ctx, ImportService_UndoImport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportServiceServer is the server API for ImportService service.
// All implementations must embed UnimplementedImportServiceServer
// for forward compatibility
type ImportServiceServer interface {
	// Upload file and initiate parsing
	UploadStatementFile(context.Context, *UploadStatementFileRequest) (*UploadStatementFileResponse, error)
	// Parse uploaded file with bank template
	ParseStatement(context.Context, *ParseStatementRequest) (*ParseStatementResponse, error)
	// Detect duplicates for imported transactions
	DetectDuplicates(context.Context, *DetectDuplicatesRequest) (*DetectDuplicatesResponse, error)
	// Execute import of reviewed transactions
	ExecuteImport(context.Context, *ExecuteImportRequest) (*ExecuteImportResponse, error)
	// List available bank templates
	ListBankTemplates(context.Context, *ListBankTemplatesRequest) (*ListBankTemplatesResponse, error)
	// Get import history
	GetImportHistory(context.Context, *GetImportHistoryRequest) (*GetImportHistoryResponse, error)
	// Undo import (within 24 hours)
	UndoImport(context.Context, *UndoImportRequest) (*UndoImportResponse, error)
	mustEmbedUnimplementedImportServiceServer()
}

// UnimplementedImportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImportServiceServer struct {
}

func (UnimplementedImportServiceServer) UploadStatementFile(context.Context, *UploadStatementFileRequest) (*UploadStatementFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStatementFile not implemented")
}
func (UnimplementedImportServiceServer) ParseStatement(context.Context, *ParseStatementRequest) (*ParseStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseStatement not implemented")
}
func (UnimplementedImportServiceServer) DetectDuplicates(context.Context, *DetectDuplicatesRequest) (*DetectDuplicatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectDuplicates not implemented")
}
func (UnimplementedImportServiceServer) ExecuteImport(context.Context, *ExecuteImportRequest) (*ExecuteImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteImport not implemented")
}
func (UnimplementedImportServiceServer) ListBankTemplates(context.Context, *ListBankTemplatesRequest) (*ListBankTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBankTemplates not implemented")
}
func (UnimplementedImportServiceServer) GetImportHistory(context.Context, *GetImportHistoryRequest) (*GetImportHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImportHistory not implemented")
}
func (UnimplementedImportServiceServer) UndoImport(context.Context, *UndoImportRequest) (*UndoImportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoImport not implemented")
}
func (UnimplementedImportServiceServer) mustEmbedUnimplementedImportServiceServer() {}

// UnsafeImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportServiceServer will
// result in compilation errors.
type UnsafeImportServiceServer interface {
	mustEmbedUnimplementedImportServiceServer()
}

func RegisterImportServiceServer(s grpc.ServiceRegistrar, srv ImportServiceServer) {
	s.RegisterService(&ImportService_ServiceDesc, srv)
}

func _ImportService_UploadStatementFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStatementFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).UploadStatementFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_UploadStatementFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).UploadStatementFile(ctx, req.(*UploadStatementFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ParseStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ParseStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ParseStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ParseStatement(ctx, req.(*ParseStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_DetectDuplicates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectDuplicatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).DetectDuplicates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_DetectDuplicates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).DetectDuplicates(ctx, req.(*DetectDuplicatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ExecuteImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ExecuteImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ExecuteImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ExecuteImport(ctx, req.(*ExecuteImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ListBankTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBankTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ListBankTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ListBankTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ListBankTemplates(ctx, req.(*ListBankTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_GetImportHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).GetImportHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_GetImportHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).GetImportHistory(ctx, req.(*GetImportHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_UndoImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).UndoImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_UndoImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).UndoImport(ctx, req.(*UndoImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportService_ServiceDesc is the grpc.ServiceDesc for ImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.import.v1.ImportService",
	HandlerType: (*ImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadStatementFile",
			Handler:    _ImportService_UploadStatementFile_Handler,
		},
		{
			MethodName: "ParseStatement",
			Handler:    _ImportService_ParseStatement_Handler,
		},
		{
			MethodName: "DetectDuplicates",
			Handler:    _ImportService_DetectDuplicates_Handler,
		},
		{
			MethodName: "ExecuteImport",
			Handler:    _ImportService_ExecuteImport_Handler,
		},
		{
			MethodName: "ListBankTemplates",
			Handler:    _ImportService_ListBankTemplates_Handler,
		},
		{
			MethodName: "GetImportHistory",
			Handler:    _ImportService_GetImportHistory_Handler,
		},
		{
			MethodName: "UndoImport",
			Handler:    _ImportService_UndoImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/import.proto",
}
