// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protobuf/v1/investment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InvestmentService_ListInvestments_FullMethodName     = "/wealthjourney.investment.v1.InvestmentService/ListInvestments"
	InvestmentService_GetInvestment_FullMethodName       = "/wealthjourney.investment.v1.InvestmentService/GetInvestment"
	InvestmentService_CreateInvestment_FullMethodName    = "/wealthjourney.investment.v1.InvestmentService/CreateInvestment"
	InvestmentService_UpdateInvestment_FullMethodName    = "/wealthjourney.investment.v1.InvestmentService/UpdateInvestment"
	InvestmentService_DeleteInvestment_FullMethodName    = "/wealthjourney.investment.v1.InvestmentService/DeleteInvestment"
	InvestmentService_AddTransaction_FullMethodName      = "/wealthjourney.investment.v1.InvestmentService/AddTransaction"
	InvestmentService_ListTransactions_FullMethodName    = "/wealthjourney.investment.v1.InvestmentService/ListTransactions"
	InvestmentService_EditTransaction_FullMethodName     = "/wealthjourney.investment.v1.InvestmentService/EditTransaction"
	InvestmentService_DeleteTransaction_FullMethodName   = "/wealthjourney.investment.v1.InvestmentService/DeleteTransaction"
	InvestmentService_GetPortfolioSummary_FullMethodName = "/wealthjourney.investment.v1.InvestmentService/GetPortfolioSummary"
	InvestmentService_UpdatePrices_FullMethodName        = "/wealthjourney.investment.v1.InvestmentService/UpdatePrices"
)

// InvestmentServiceClient is the client API for InvestmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvestmentServiceClient interface {
	// List all investments in a wallet
	ListInvestments(ctx context.Context, in *ListInvestmentsRequest, opts ...grpc.CallOption) (*ListInvestmentsResponse, error)
	// Get a specific investment
	GetInvestment(ctx context.Context, in *GetInvestmentRequest, opts ...grpc.CallOption) (*GetInvestmentResponse, error)
	// Create a new investment holding
	CreateInvestment(ctx context.Context, in *CreateInvestmentRequest, opts ...grpc.CallOption) (*CreateInvestmentResponse, error)
	// Update investment details
	UpdateInvestment(ctx context.Context, in *UpdateInvestmentRequest, opts ...grpc.CallOption) (*UpdateInvestmentResponse, error)
	// Delete an investment
	DeleteInvestment(ctx context.Context, in *DeleteInvestmentRequest, opts ...grpc.CallOption) (*DeleteInvestmentResponse, error)
	// Add a buy/sell transaction
	AddTransaction(ctx context.Context, in *AddTransactionRequest, opts ...grpc.CallOption) (*AddTransactionResponse, error)
	// List transactions for an investment
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	// Edit a transaction
	EditTransaction(ctx context.Context, in *EditTransactionRequest, opts ...grpc.CallOption) (*EditTransactionResponse, error)
	// Delete a transaction
	DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteTransactionResponse, error)
	// Get portfolio summary
	GetPortfolioSummary(ctx context.Context, in *GetPortfolioSummaryRequest, opts ...grpc.CallOption) (*GetPortfolioSummaryResponse, error)
	// Update current prices (manual or automatic)
	UpdatePrices(ctx context.Context, in *UpdatePricesRequest, opts ...grpc.CallOption) (*UpdatePricesResponse, error)
}

type investmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvestmentServiceClient(cc grpc.ClientConnInterface) InvestmentServiceClient {
	return &investmentServiceClient{cc}
}

func (c *investmentServiceClient) ListInvestments(ctx context.Context, in *ListInvestmentsRequest, opts ...grpc.CallOption) (*ListInvestmentsResponse, error) {
	out := new(ListInvestmentsResponse)
	err := c.cc.Invoke(ctx, InvestmentService_ListInvestments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) GetInvestment(ctx context.Context, in *GetInvestmentRequest, opts ...grpc.CallOption) (*GetInvestmentResponse, error) {
	out := new(GetInvestmentResponse)
	err := c.cc.Invoke(ctx, InvestmentService_GetInvestment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) CreateInvestment(ctx context.Context, in *CreateInvestmentRequest, opts ...grpc.CallOption) (*CreateInvestmentResponse, error) {
	out := new(CreateInvestmentResponse)
	err := c.cc.Invoke(ctx, InvestmentService_CreateInvestment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) UpdateInvestment(ctx context.Context, in *UpdateInvestmentRequest, opts ...grpc.CallOption) (*UpdateInvestmentResponse, error) {
	out := new(UpdateInvestmentResponse)
	err := c.cc.Invoke(ctx, InvestmentService_UpdateInvestment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) DeleteInvestment(ctx context.Context, in *DeleteInvestmentRequest, opts ...grpc.CallOption) (*DeleteInvestmentResponse, error) {
	out := new(DeleteInvestmentResponse)
	err := c.cc.Invoke(ctx, InvestmentService_DeleteInvestment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) AddTransaction(ctx context.Context, in *AddTransactionRequest, opts ...grpc.CallOption) (*AddTransactionResponse, error) {
	out := new(AddTransactionResponse)
	err := c.cc.Invoke(ctx, InvestmentService_AddTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, InvestmentService_ListTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) EditTransaction(ctx context.Context, in *EditTransactionRequest, opts ...grpc.CallOption) (*EditTransactionResponse, error) {
	out := new(EditTransactionResponse)
	err := c.cc.Invoke(ctx, InvestmentService_EditTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...grpc.CallOption) (*DeleteTransactionResponse, error) {
	out := new(DeleteTransactionResponse)
	err := c.cc.Invoke(ctx, InvestmentService_DeleteTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) GetPortfolioSummary(ctx context.Context, in *GetPortfolioSummaryRequest, opts ...grpc.CallOption) (*GetPortfolioSummaryResponse, error) {
	out := new(GetPortfolioSummaryResponse)
	err := c.cc.Invoke(ctx, InvestmentService_GetPortfolioSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *investmentServiceClient) UpdatePrices(ctx context.Context, in *UpdatePricesRequest, opts ...grpc.CallOption) (*UpdatePricesResponse, error) {
	out := new(UpdatePricesResponse)
	err := c.cc.Invoke(ctx, InvestmentService_UpdatePrices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvestmentServiceServer is the server API for InvestmentService service.
// All implementations must embed UnimplementedInvestmentServiceServer
// for forward compatibility
type InvestmentServiceServer interface {
	// List all investments in a wallet
	ListInvestments(context.Context, *ListInvestmentsRequest) (*ListInvestmentsResponse, error)
	// Get a specific investment
	GetInvestment(context.Context, *GetInvestmentRequest) (*GetInvestmentResponse, error)
	// Create a new investment holding
	CreateInvestment(context.Context, *CreateInvestmentRequest) (*CreateInvestmentResponse, error)
	// Update investment details
	UpdateInvestment(context.Context, *UpdateInvestmentRequest) (*UpdateInvestmentResponse, error)
	// Delete an investment
	DeleteInvestment(context.Context, *DeleteInvestmentRequest) (*DeleteInvestmentResponse, error)
	// Add a buy/sell transaction
	AddTransaction(context.Context, *AddTransactionRequest) (*AddTransactionResponse, error)
	// List transactions for an investment
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	// Edit a transaction
	EditTransaction(context.Context, *EditTransactionRequest) (*EditTransactionResponse, error)
	// Delete a transaction
	DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteTransactionResponse, error)
	// Get portfolio summary
	GetPortfolioSummary(context.Context, *GetPortfolioSummaryRequest) (*GetPortfolioSummaryResponse, error)
	// Update current prices (manual or automatic)
	UpdatePrices(context.Context, *UpdatePricesRequest) (*UpdatePricesResponse, error)
	mustEmbedUnimplementedInvestmentServiceServer()
}

// UnimplementedInvestmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInvestmentServiceServer struct {
}

func (UnimplementedInvestmentServiceServer) ListInvestments(context.Context, *ListInvestmentsRequest) (*ListInvestmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInvestments not implemented")
}
func (UnimplementedInvestmentServiceServer) GetInvestment(context.Context, *GetInvestmentRequest) (*GetInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvestment not implemented")
}
func (UnimplementedInvestmentServiceServer) CreateInvestment(context.Context, *CreateInvestmentRequest) (*CreateInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvestment not implemented")
}
func (UnimplementedInvestmentServiceServer) UpdateInvestment(context.Context, *UpdateInvestmentRequest) (*UpdateInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvestment not implemented")
}
func (UnimplementedInvestmentServiceServer) DeleteInvestment(context.Context, *DeleteInvestmentRequest) (*DeleteInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInvestment not implemented")
}
func (UnimplementedInvestmentServiceServer) AddTransaction(context.Context, *AddTransactionRequest) (*AddTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTransaction not implemented")
}
func (UnimplementedInvestmentServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedInvestmentServiceServer) EditTransaction(context.Context, *EditTransactionRequest) (*EditTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTransaction not implemented")
}
func (UnimplementedInvestmentServiceServer) DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTransaction not implemented")
}
func (UnimplementedInvestmentServiceServer) GetPortfolioSummary(context.Context, *GetPortfolioSummaryRequest) (*GetPortfolioSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolioSummary not implemented")
}
func (UnimplementedInvestmentServiceServer) UpdatePrices(context.Context, *UpdatePricesRequest) (*UpdatePricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrices not implemented")
}
func (UnimplementedInvestmentServiceServer) mustEmbedUnimplementedInvestmentServiceServer() {}

// UnsafeInvestmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvestmentServiceServer will
// result in compilation errors.
type UnsafeInvestmentServiceServer interface {
	mustEmbedUnimplementedInvestmentServiceServer()
}

func RegisterInvestmentServiceServer(s grpc.ServiceRegistrar, srv InvestmentServiceServer) {
	s.RegisterService(&InvestmentService_ServiceDesc, srv)
}

func _InvestmentService_ListInvestments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvestmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).ListInvestments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_ListInvestments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).ListInvestments(ctx, req.(*ListInvestmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_GetInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).GetInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_GetInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).GetInvestment(ctx, req.(*GetInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_CreateInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).CreateInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_CreateInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).CreateInvestment(ctx, req.(*CreateInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_UpdateInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).UpdateInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_UpdateInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).UpdateInvestment(ctx, req.(*UpdateInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_DeleteInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).DeleteInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_DeleteInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).DeleteInvestment(ctx, req.(*DeleteInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_AddTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).AddTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_AddTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).AddTransaction(ctx, req.(*AddTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_EditTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).EditTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_EditTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).EditTransaction(ctx, req.(*EditTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_DeleteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).DeleteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_DeleteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).DeleteTransaction(ctx, req.(*DeleteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_GetPortfolioSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).GetPortfolioSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_GetPortfolioSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).GetPortfolioSummary(ctx, req.(*GetPortfolioSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvestmentService_UpdatePrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestmentServiceServer).UpdatePrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestmentService_UpdatePrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestmentServiceServer).UpdatePrices(ctx, req.(*UpdatePricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvestmentService_ServiceDesc is the grpc.ServiceDesc for InvestmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvestmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthjourney.investment.v1.InvestmentService",
	HandlerType: (*InvestmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInvestments",
			Handler:    _InvestmentService_ListInvestments_Handler,
		},
		{
			MethodName: "GetInvestment",
			Handler:    _InvestmentService_GetInvestment_Handler,
		},
		{
			MethodName: "CreateInvestment",
			Handler:    _InvestmentService_CreateInvestment_Handler,
		},
		{
			MethodName: "UpdateInvestment",
			Handler:    _InvestmentService_UpdateInvestment_Handler,
		},
		{
			MethodName: "DeleteInvestment",
			Handler:    _InvestmentService_DeleteInvestment_Handler,
		},
		{
			MethodName: "AddTransaction",
			Handler:    _InvestmentService_AddTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _InvestmentService_ListTransactions_Handler,
		},
		{
			MethodName: "EditTransaction",
			Handler:    _InvestmentService_EditTransaction_Handler,
		},
		{
			MethodName: "DeleteTransaction",
			Handler:    _InvestmentService_DeleteTransaction_Handler,
		},
		{
			MethodName: "GetPortfolioSummary",
			Handler:    _InvestmentService_GetPortfolioSummary_Handler,
		},
		{
			MethodName: "UpdatePrices",
			Handler:    _InvestmentService_UpdatePrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/investment.proto",
}
